#!/bin/bash
set -e

# Demo: KRO + ASO Working Together
# This script demonstrates how one simple API call creates multiple Azure resources

echo "🎯 Testing KRO + ASO Integration"
echo "================================"
echo ""

# Check prerequisites
echo "✅ Checking prerequisites..."
kubectl get pods -n kro --no-headers 2>/dev/null | grep -q Running || { echo "❌ KRO not running"; exit 1; }
kubectl get pods -n azureserviceoperator-system --no-headers 2>/dev/null | grep -q Running || { echo "❌ ASO not running"; exit 1; }

echo "✅ KRO is running"
echo "✅ ASO is running"
echo ""

# Get tenant ID
TENANT_ID=$(az account show --query tenantId -o tsv 2>/dev/null)
if [ -z "$TENANT_ID" ]; then
    echo "❌ Not logged in to Azure. Please run: az login"
    exit 1
fi

echo "📌 Azure Tenant ID: $TENANT_ID"
echo ""

# Step 1: Install the KRO template
echo "📦 Step 1: Installing KRO Infrastructure Composition Template"
echo "   This defines a reusable API for creating full infrastructure stacks"
echo ""
kubectl apply -f kro-templates/infra-composition.yaml

echo ""
echo "⏳ Waiting for KRO to register the new API..."
sleep 5

# Step 2: Create an instance using the simple API
echo ""
echo "🚀 Step 2: Creating Infrastructure Stack with ONE Simple API Call"
echo "   This will create:"
echo "   - 1 Resource Group"
echo "   - 1 Storage Account"
echo "   - 1 Key Vault"
echo "   - 1 Log Analytics Workspace"
echo ""

cat <<EOF | kubectl apply -f -
apiVersion: kro.run/v1alpha1
kind: InfraComposition
metadata:
  name: demo-infra
spec:
  projectName: demo
  location: northeurope
  tenantId: "$TENANT_ID"
  owner: shola
EOF

echo ""
echo "✅ InfraComposition 'demo-infra' created!"
echo ""

# Step 3: Watch KRO generate ASO resources
echo "👀 Step 3: Watching KRO generate ASO resources..."
echo ""
sleep 5

echo "📋 ASO Resources generated by KRO:"
kubectl get resourcegroup,storageaccount,vault,workspace -l kro.run/parent=demo-infra 2>/dev/null || \
kubectl get resourcegroup,storageaccount,vault,workspace | grep demo

echo ""
echo "⏳ Step 4: Watching ASO create Azure resources (this takes ~30 seconds)..."
echo ""

# Monitor for 30 seconds
for i in {1..6}; do
    echo "   Checking... ($i/6)"
    kubectl get resourcegroup,storageaccount,vault,workspace 2>/dev/null | grep demo | grep -E "True.*Succeeded" && break
    sleep 5
done

echo ""
echo "📊 Final Status:"
kubectl get resourcegroup,storageaccount,vault,workspace 2>/dev/null | grep demo

echo ""
echo "✨ Demo Complete!"
echo ""
echo "📈 What just happened:"
echo "   1. KRO Template: 1 ResourceGroup definition (the template)"
echo "   2. Simple API: 1 InfraComposition resource (user request)"
echo "   3. KRO Generated: 4 ASO resources automatically"
echo "   4. ASO Created: 4 Azure resources in your subscription"
echo ""
echo "🔍 Verify in Azure:"
echo "   az group show --name rg-demo"
echo "   az storage account show --name stdemo001 --resource-group rg-demo"
echo ""
echo "🧹 Cleanup:"
echo "   kubectl delete infracomposition demo-infra"
echo "   (This will delete all 4 Azure resources automatically!)"
