apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
- ../../base

nameSuffix: -dev

commonLabels:
  environment: development

patches:
- patch: |-
    - op: replace
      path: /spec/tags
      value:
        Environment: Development
        ManagedBy: Kustomize-ASO
        CostCenter: DevTeam
  target:
    kind: ResourceGroup
    name: kustomize-app-rg

- patch: |-
    - op: replace
      path: /spec/sku/name
      value: Standard_LRS
  target:
    kind: StorageAccount
    name: kustomizeappsa
